### ISSUE TITLE
404 Page Not Found View

### ISSUE THREAD

**Issue by Hanya-Ahmad** [codescalersinternships/Flyspray#75]
### Description:
 Create a 404 page not found when attempting to access a nonexistent endpoint.
### Tasks
- Design the page.
- Provide clear error message.
- Provide navigation options to the user ( i.e: a button to go to the homepage, a button to go to the previous page).

**Comment by Mahmoud-Emad** [comment]
Should be implemented by @Hanya-Ahmad
